vim.opt.runtimepath:prepend(vim.fn.getcwd())
local original_cwd=vim.fn.getcwd()
local function same_dir(a,b) return vim.uv.fs_realpath(a)==vim.uv.fs_realpath(b) end
local root=vim.fn.tempname()
vim.fn.mkdir(root..'/dir','p')
vim.fn.writefile({'x'},root..'/dir/a.txt')
vim.fn.writefile({'x'},root..'/other.txt')
local tree=require('svgtree')
tree.setup({renderer='terminal',window={width=24}})
tree.open(root)
local render=require('svgtree.render')
local win=vim.api.nvim_get_current_win()
assert(vim.api.nvim_win_get_width(win)==24,'configured initial width')
vim.api.nvim_win_set_cursor(win,{1,0})
vim.api.nvim_feedkeys('l','x',false)
local expanded=render.snapshot()
assert(expanded.expanded[root..'/dir'],'directory expansion saved')
vim.api.nvim_win_set_cursor(win,{2,0})
vim.api.nvim_win_set_width(win,28)
tree.close()
tree.open(root)
local saved=render.snapshot()
assert(saved.expanded[root..'/dir'] and saved.selected==root..'/dir/a.txt','reopen restores expansion and selection')
assert(vim.api.nvim_win_get_width(vim.api.nvim_get_current_win())==28,'reopen restores cell width')
tree.close()
vim.fn.delete(root..'/dir/a.txt')
tree.open(root)
assert(render.snapshot().selected~=root..'/dir/a.txt','deleted selection reconciles')
tree.close()
tree.open(root)
vim.api.nvim_win_set_cursor(vim.api.nvim_get_current_win(),{1,0})
vim.api.nvim_feedkeys('.', 'x', false)
assert(tree.root()==root..'/dir' and same_dir(vim.fn.getcwd(),root..'/dir'),'dot changes terminal root and editor directory')
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes('<BS>',true,false,true),'x',false)
assert(tree.root()==root and same_dir(vim.fn.getcwd(),root),'backspace moves terminal root and editor directory upward')
tree.close()
tree.open()
assert(same_dir(tree.root(),root),'terminal tree reopens at the current editor directory')
tree.close()
vim.api.nvim_set_current_dir(original_cwd)
vim.fn.delete(root,'rf')
print('terminal session ok')
