vim.opt.runtimepath:prepend(vim.fn.getcwd())
local api = vim.env.SVGTREE_API_CHECKOUT or (vim.fn.getcwd() .. '/../native-explorer-api')
if vim.fn.filereadable(api .. '/lua/sprite/input.lua') == 1 then
  package.path = api .. '/lua/?.lua;' .. api .. '/lua/?/init.lua;' .. package.path
end
local Keys = require('svgtree.keys')
assert(Keys.search({{id='a',text='A[1].lua'}}, '[1]')[1] == 'a')
assert(not pcall(Keys.new, {g='next'}, 1000), 'ambiguous prefix rejected')
if not pcall(require, 'sprite.input') then print('native keys core ok (Sprite input unavailable)'); return end
local k = Keys.new(nil, 1000)
local function input(key, text, time) return k:feed({type='input',key=key,text=text}, time or 0) end
assert(input('j','j') == 'next')
assert(input('k','k') == 'previous')
assert(input('g','g',1) == nil)
assert(input('g','g',2) == 'first')
assert(input('g','g',3) == nil)
assert(input('g','g',1004) == nil)
assert(input('G','G') == 'last')
assert(input('down',nil) == 'next')
assert(input('home',nil) == 'first')
assert(input('ctrl-d',nil) == 'half_down')
assert(input('ctrl-u',nil) == 'half_up')
assert(input('.', '.') == 'focus_root')
assert(input('backspace',nil) == 'parent_root')
assert(input('ctrl-w',nil) == nil)
assert(input('l','l') == 'focus_editor')
assert(input('ctrl-w',nil) == nil)
assert(input('ctrl-l',nil) == 'focus_editor', 'supports Neovim <C-l> window mapping')
local right = Keys.new(nil, 1000, 'right')
assert(right:feed({type='input',key='ctrl-w'},0) == nil)
assert(right:feed({type='input',key='ctrl-h'},1) == 'focus_editor', 'supports Neovim <C-h> window mapping')
assert(input('escape',nil) == 'close')
assert(input('enter','\n') == 'open')
assert(input('unknown',nil) == nil)
assert(input('y','j') == 'next', 'produced text wins')
assert(input('j','é') == nil)
assert(k:feed({type='blur'},0) == nil)
assert(input('g','g',0) == nil)
k:reset(); assert(input('g','g',1) == nil)
local remap = Keys.new({j='previous',k=false},1000)
assert(remap:feed({type='input',key='j',text='j'},0) == 'previous')
assert(remap:feed({type='input',key='k',text='k'},1) == nil)
assert(not pcall(Keys.new, {g='next'}, 1000), 'ambiguous prefix rejected')
local space=Keys.new({['<Space>']='refresh',['<Enter>']='close'},1000)
assert(space:feed({type='input',key='space',text=' '},0)=='refresh')
assert(space:feed({type='input',key='enter',text='\n'},0)=='close')
assert(not pcall(Keys.new,{['<Foo>']='open'}), 'unknown key notation rejected')
local less=Keys.new({['<lt>']='refresh'},1000)
assert(less:feed({type='input',key='<',text='<'},0)=='refresh', '<lt> binding follows produced text')
local triple=Keys.new({abc='refresh'},1000)
assert(triple:feed({type='input',key='a',text='a'},1)==nil)
assert(triple:feed({type='input',key='b',text='b'},2)==nil)
assert(triple:feed({type='input',key='c',text='c'},3)=='refresh')
assert(Keys.search({{id='a',text='A[1].lua'},{id='b',text='other'}}, '[1]')[1] == 'a')
assert(Keys.search({{id='é',text='Éclair'}}, 'é')[1] == 'é')
print('native keys ok')
