vim.opt.runtimepath:prepend(vim.fn.getcwd())

local svgtree = require('svgtree')
local original_cwd = vim.fn.getcwd()
local function same_dir(a, b) return vim.uv.fs_realpath(a) == vim.uv.fs_realpath(b) end
local first_root = vim.fn.tempname()
local second_root = vim.fn.tempname()
vim.fn.mkdir(first_root, 'p')
vim.fn.mkdir(second_root, 'p')

assert(svgtree.root() == nil, 'closed tree must have no root')
svgtree.open(first_root)
assert(svgtree.root() == first_root, 'open tree must expose its root')
assert(same_dir(vim.fn.getcwd(), first_root), 'opening a root must change the editor directory')
svgtree.open(second_root)
assert(svgtree.root() == second_root, 'reopened tree must expose its new root')
assert(same_dir(vim.fn.getcwd(), second_root), 'switching roots must change the editor directory')
svgtree.close()
assert(svgtree.root() == nil, 'closed tree must clear its root')
svgtree.open()
assert(same_dir(svgtree.root(), second_root), 'opening without a path must keep the last root')
svgtree.close()

vim.api.nvim_set_current_dir(original_cwd)
vim.fn.delete(first_root, 'rf')
vim.fn.delete(second_root, 'rf')
print('test-root: ALL PASS')
