name: tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  core:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        nvim: ['v0.11.0', stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: HundredBillion/sprite.nvim
          ref: e4b272dcff25f062f4c6d699cbc44e71807344bc
          path: .test-deps/sprite.nvim
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: ${{ matrix.nvim }}
      - run: SVGTREE_API_CHECKOUT=.test-deps/sprite.nvim SVGTREE_NVIM='${{ steps.nvim.outputs.executable }}' bash scripts/test-core.sh

  graphics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: HundredBillion/sprite.nvim
          ref: e4b272dcff25f062f4c6d699cbc44e71807344bc
          path: .test-deps/sprite.nvim
      - run: sudo apt-get update && sudo apt-get install -y librsvg2-bin
      - uses: rhysd/action-setup-vim@v1
        id: nvim
        with:
          neovim: true
          version: nightly
      - run: SVGTREE_API_CHECKOUT=.test-deps/sprite.nvim SVGTREE_NVIM='${{ steps.nvim.outputs.executable }}' bash scripts/test.sh
